name: Update Website Screenshot

on:
  schedule:
    - cron: '0 * * * *'
  push:

jobs:
  update-screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Take screenshot
        uses: karol-brejna-i/webpage-screenshot-action@v1.1.2 
        with:
          url: 'https://cyanone.art/'
          output: 'assets/img/screenshot.png'

      - name: Update og:image in index.html
        run: |
          sed -i 's|<meta property="og:image" content=".*"|<meta property="og:image" content="assets/img/screenshot.png"|' index.html

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push if there are changes
        run: |
          git add .
          git commit -m "Update website screenshot" -a || exit 0
          git push
