name: Update Website Screenshot

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  push:

jobs:
  take_screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Puppeteer
        run: |
          npm install puppeteer

      - name: Take screenshot of cyanone.art
        run: |
          node ./scripts/take-screenshot.js

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Check if screenshot has changed
        run: |
          mkdir -p assets/img
          mv screenshot.png assets/img/screenshot.png
          git fetch origin
          git diff --exit-code assets/img/screenshot.png || echo "Screenshot has changed"

      - name: Commit and push screenshot if changed
        if: ${{ success() && steps.screenshot_change.outcome == 'failure' }}
        run: |
          git add assets/img/screenshot.png
          git commit -m "Update screenshot"
          git push
