name: Update Website Screenshot

on:
  schedule:
    - cron: '0 * * * *'
  push:

jobs:
  update-screenshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Take screenshot
        uses: swinton/screenshot-website@v1.x
        with:
          source: https://cyanone.art
          destination: screenshot.png
          width: 800
          full-page: false
          delay: 5

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: screenshot.png
          path: screenshot.png
          
      - name: Download a Build Artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: screenshot.png
          path: assets/img


      - name: Update og:image in index.html
        run: |
          sed -i 's|<meta property="og:image" content=".*"|<meta property="og:image" content="https://cyanone.art/assets/img/screenshot.png"|' index.html

      - name: Configure git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit and push if there are changes
        run: |
          git add .
          git commit -m "Update website screenshot" -a || exit 0
          git push
